const kriminalKonflikData = [
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Cendrawasih Raya Perbatasan RW.006 dan RW.007",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11612,
    "lng": 106.7214
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Komplek Kebersihan RT.013/010",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.12702,
    "lng": 106.7146
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Menceng Raya Perbatasan antara Kel. Tegal Alur dan Cengkareng Barat RW.009",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11602,
    "lng": 106.7177
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Raya Kamal depan Komplek Taman Kencana RW.012",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11492,
    "lng": 106.71796
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Daan Mogot depan Komplek Imigrasi RW.014",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11556,
    "lng": 106.72356
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Flamboyan Raya RW.008,RW.010 dan RW.014",
    "pelaku": "Siswa SMK 53 Jakarta",
    "keterangan": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "lat": -6.10886,
    "lng": 106.71802
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Bambu Larangan Perbatasan Kel. Pegadungan dan Cengkareng Barat RW.005",
    "pelaku": "Siswa SMK 1 Cengkareng",
    "keterangan": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "lat": -6.11886,
    "lng": 106.72914
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Utama III RW.001 dan RW.003, tersambung ke Jl. Cendrawasih V RW.006",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1183,
    "lng": 106.72828
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Barat",
    "tanggal": "",
    "lokasi": "Jl. Kamal Raya RT.006/003",
    "pelaku": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "keterangan": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "lat": -6.12152,
    "lng": 106.7241
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Timur",
    "tanggal": "",
    "lokasi": "Jl. Nurul Amal RW.05",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.12008,
    "lng": 106.71746
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Timur",
    "tanggal": "",
    "lokasi": "Jl. Daan Mogot RW.001",
    "pelaku": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "keterangan": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "lat": -6.10734,
    "lng": 106.71994
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Timur",
    "tanggal": "",
    "lokasi": "Jl. Jati Raya RT.005/012",
    "pelaku": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "keterangan": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "lat": -6.1132,
    "lng": 106.7302
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Timur",
    "tanggal": "",
    "lokasi": "Jl. Masjud Nurul Huda RT.003/001",
    "pelaku": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "keterangan": "Kelompok Pelajar biasanya melakukan aksi tawuran setelah pulang sekolah Pukul 13.00 s.d 17.00 WIB",
    "lat": -6.1269,
    "lng": 106.72012
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Timur",
    "tanggal": "",
    "lokasi": "RW.009 Kelurahan Cengkareng Timur",
    "pelaku": "Kelompok AIRBUD",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.1186,
    "lng": 106.73072
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Cengkareng Timur",
    "tanggal": "",
    "lokasi": "RW.012 Kelurahan Cengkareng Timur",
    "pelaku": "Kelompok DOGI STRADA",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.1236,
    "lng": 106.71856
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Rawa Buaya",
    "tanggal": "",
    "lokasi": "Jl. Cempaka arah Cengkareng Drain RW.011, tanggul rel kereta berbatasan dengan wilayah Kembangan Utara",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.12536,
    "lng": 106.72924
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Rawa Buaya",
    "tanggal": "",
    "lokasi": "Jl. Nangka RW.002, berbatasan dan bersebrangan dengan warga Cengkareng Timur",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1096,
    "lng": 106.7237
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Rawa Buaya",
    "tanggal": "",
    "lokasi": "Jl. Pandu RW.009 depan rumah pompa",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1089,
    "lng": 106.7297
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "Kel. Rawa Buaya",
    "tanggal": "",
    "lokasi": "Jl. Daan Mogot depan VITTORIA jalan Outer Ring Road RW.003",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.12048,
    "lng": 106.7196
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Duri Kosambi",
    "tanggal": "",
    "lokasi": "Jl.Pondok Randu dekat Tinja RW.002 Green Lake City",
    "pelaku": "Remaja / Kelompok Anak Muda RW.002",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.12008,
    "lng": 106.7273
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kapuk",
    "tanggal": "",
    "lokasi": "Jl. Pedongkelan Raya Tanggul Barat RW.012",
    "pelaku": "Remaja / Kelompok Anak Muda RW.012",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.11476,
    "lng": 106.71792
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kapuk",
    "tanggal": "",
    "lokasi": "Jl. Pedongkelan Raya Tanggul Barat RW.013",
    "pelaku": "Remaja / Kelompok Anak Muda RW.013",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.1259,
    "lng": 106.7168
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kapuk",
    "tanggal": "",
    "lokasi": "Jl. Dolar RW.014 Perbatasan RW.007 dan RW.011",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11152,
    "lng": 106.72144
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kapuk",
    "tanggal": "",
    "lokasi": "Jl. Rawa Gabus RT.007/011",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.125,
    "lng": 106.72722
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kapuk",
    "tanggal": "",
    "lokasi": "Jl. Kapuk Raya RW.003",
    "pelaku": "Remaja / Kelompok Anak Muda RW.002 dan RW.005",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.10938,
    "lng": 106.72024
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kedaung Kali Angke",
    "tanggal": "",
    "lokasi": "Jl. Daan Mogot KM.11 (Halte Taman Kota)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1072,
    "lng": 106.7206
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kedaung Kali Angke",
    "tanggal": "",
    "lokasi": "Jl. Daan Mogot KM. 10 (Jembatan Pesing berbatasan dengan Kelurahan Wijaya Kusuma Kelurahan Kedoya Utara)",
    "pelaku": "Remaja / Kelompok Anak Muda RW.005",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.10746,
    "lng": 106.72446
  },
  {
    "type": "Tawuran",
    "kecamatan": "Cengkareng",
    "kelurahan": "kel. Kedaung Kali Angke",
    "tanggal": "",
    "lokasi": "Jl. Pool PPD RT.010/002",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.12614,
    "lng": 106.72356
  },
  {
    "type": "Tawuran",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. Tomang",
    "tanggal": "",
    "lokasi": "Jl. rawa kepa Rw 13, berbatasan dengan kelurahan jatipulo",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.17442,
    "lng": 106.79164
  },
  {
    "type": "Tawuran",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. Tomang",
    "tanggal": "",
    "lokasi": "Jl. tanjung gedong Rw 08 dan Rw 016",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.16514,
    "lng": 106.78712
  },
  {
    "type": "Tawuran",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. Tomang",
    "tanggal": "",
    "lokasi": "Jl. tawakal raya Rw08 dan Rw 016, sekolah perti",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.16836,
    "lng": 106.7837
  },
  {
    "type": "Tawuran",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. grogol",
    "tanggal": "",
    "lokasi": "Jl. dr. semeru raya (depan masjid al-muhajirin)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.18108,
    "lng": 106.78756
  },
  {
    "type": "Tawuran",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. grogol",
    "tanggal": "",
    "lokasi": "Jl. kyai tapa (depan taman masjid nurul haq)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.17528,
    "lng": 106.79592
  },
  {
    "type": "Tawuran",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. jelambar baru",
    "tanggal": "",
    "lokasi": "Jl. semeru ujung slatumenten (depan apart latumenten)",
    "pelaku": "anak Rw 10, kel. grogol dengan anak jelambar baru",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.17064,
    "lng": 106.79892
  },
  {
    "type": "Tawuran",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. wijaya kusuma",
    "tanggal": "",
    "lokasi": "Jl. pangeran Tubagus angke Rt011 Rw05 kelurahan wijaya kusuma",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.16544,
    "lng": 106.78682
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. glodok",
    "tanggal": "",
    "lokasi": "Jl. arteri Kali krukut Rt014/05",
    "pelaku": "Anak Tanah Sereal Vs Anak Krukut",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 01.00 s.d 04.00 WIB",
    "lat": -6.1589,
    "lng": 106.75634
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. keagungan",
    "tanggal": "",
    "lokasi": "Jl. keadilan Rw 02 (lintasan)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.16224,
    "lng": 106.76388
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. keagungan",
    "tanggal": "",
    "lokasi": "Jl. keagungan/kali Timbul (Rw 04)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.16178,
    "lng": 106.76528
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. keagungan",
    "tanggal": "",
    "lokasi": "Jl. keamanan Raya (Rw 08,03,07,06) (lintasan), Tahun 2025 Kejadian (Rt 005/07) dan Tahun 2026 (RT001/06)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.17176,
    "lng": 106.76388
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. keagungan",
    "tanggal": "",
    "lokasi": "Jl. kerajinan I, Jl Kerajinan II (Rw 09)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1667,
    "lng": 106.75224
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. krukut",
    "tanggal": "",
    "lokasi": "Jl. ketapang Utara I",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1769,
    "lng": 106.75368
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. krukut",
    "tanggal": "",
    "lokasi": "Jl. Arteri kali krukut, kel krukut",
    "pelaku": "Anak Tanah Sereal Vs Anak Krukut",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 01.00 s.d 04.00 WIB",
    "lat": -6.15896,
    "lng": 106.76296
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "Kel.Maphar",
    "tanggal": "",
    "lokasi": "Jl.Sukarjo Wiryo Pranoto",
    "pelaku": "Anak Batu Ceper Vs Anak Maphar",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 01.00 s.d 04.00 WIB",
    "lat": -6.17308,
    "lng": 106.75908
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "Kel.Maphar",
    "tanggal": "",
    "lokasi": "Jl. Tamansari Raya kel. maphar & kel. Tamansari",
    "pelaku": "Anak Karanganyer Vs Anak Taman Sari",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 01.00 s.d 04.00 WIB",
    "lat": -6.15848,
    "lng": 106.75704
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tamansari",
    "kelurahan": "Kel. Tangki",
    "tanggal": "",
    "lokasi": "JI.Mangga Besar IX Depan Indomart RW 05",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.16562,
    "lng": 106.7602
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tambora",
    "kelurahan": "Kel.Angke",
    "tanggal": "",
    "lokasi": "JI.Tanah Sereal Raya",
    "pelaku": "warga kp taman sari dan warga tanah sereal",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.16048,
    "lng": 106.80714
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tambora",
    "kelurahan": "Kel.Duri Utara",
    "tanggal": "",
    "lokasi": "JI. Duri Utara Raya (warga Duri Utara warga Kali Anyar dan Jembes)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.15952,
    "lng": 106.79728
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tambora",
    "kelurahan": "Kel.Jembatan Besi",
    "tanggal": "",
    "lokasi": "JI.Raya Jembatan Besi RW 03/RW 07(depan Palang Pintu Kereta)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1513,
    "lng": 106.7978
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tambora",
    "kelurahan": "Kel.Kali Anyar",
    "tanggal": "",
    "lokasi": "JI. Setia Kawan IIIA BKB atas tanggul RT. 007 RW. 08 (dekat perlintasan kereta api)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.14856,
    "lng": 106.80484
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tambora",
    "kelurahan": "Kel.Krendang",
    "tanggal": "",
    "lokasi": "JI.Krendang Raya (Pertigaan)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.16438,
    "lng": 106.79384
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tambora",
    "kelurahan": "Kel.Pekojan",
    "tanggal": "",
    "lokasi": "Pintu kereta Angke perbatasan Pekojan RT.08 RW.07 dengan Angke",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.14482,
    "lng": 106.80784
  },
  {
    "type": "Tawuran",
    "kecamatan": "Tambora",
    "kelurahan": "Kel.Pekojan",
    "tanggal": "",
    "lokasi": "Gedong Panjang RT.13 RW.10 dengan Jakarta Utara",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.15964,
    "lng": 106.79906
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kebon Jeruk",
    "kelurahan": "Kel.Kebon Jeruk",
    "tanggal": "",
    "lokasi": "JI. Kebon Jeruk Raya (perbatasan Wilayah RW 005 & RW 009)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.19306,
    "lng": 106.76372
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kebon Jeruk",
    "kelurahan": "Kel.Kedoya Utara",
    "tanggal": "",
    "lokasi": "JI.Boluverd Perumahan Green Garden RT 10 RW 10 (perbatasan antara Kedoya Selatan dan Kedoya Utara)",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.19304,
    "lng": 106.775
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kebon Jeruk",
    "kelurahan": "Kel.Kedoya Utara",
    "tanggal": "",
    "lokasi": "Jl. Daan Mogot Pesing Koneng Kedoya Utara",
    "pelaku": "Warga Pesing Kedoya dgn Warga Cengkareng",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.19194,
    "lng": 106.77438
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kebon Jeruk",
    "kelurahan": "Kel.Kedoya Utara",
    "tanggal": "",
    "lokasi": "Jl. Kedoya Utara Raya kel. Kedoya Utara",
    "pelaku": "Warga Pesing Gadog dengan kelompok motor yang melintas",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.18946,
    "lng": 106.76256
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kebon Jeruk",
    "kelurahan": "Kel.Kelapa Dua",
    "tanggal": "",
    "lokasi": "JI.Anggrek bawah kel. Kelapa dua Rw. 02- Perbatasan kel. Sukabumi Utara",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.19634,
    "lng": 106.76502
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kebon Jeruk",
    "kelurahan": "Kel.Kelapa Dua",
    "tanggal": "",
    "lokasi": "JI.pos pengumben raya perbatasan kelapa dua dan sukut",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.18072,
    "lng": 106.76918
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kebon Jeruk",
    "kelurahan": "Kel.Sukabumi Selatan",
    "tanggal": "",
    "lokasi": "JI.Pos Pengumben Raya",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.19884,
    "lng": 106.77274
  },
  {
    "type": "Tawuran",
    "kecamatan": "Palmerah",
    "kelurahan": "Kel.Kemanggisan",
    "tanggal": "",
    "lokasi": "JI.Inspeksi Grogol rt. 009, dan 011 rw 03",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1938,
    "lng": 106.79634
  },
  {
    "type": "Tawuran",
    "kecamatan": "Palmerah",
    "kelurahan": "Kel.Kota Bambu Selatan",
    "tanggal": "",
    "lokasi": "JI. KS Tubun RT.002 RW.03 dan RT.007 RW.02",
    "pelaku": "warga",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.20926,
    "lng": 106.80282
  },
  {
    "type": "Tawuran",
    "kecamatan": "Palmerah",
    "kelurahan": "Kel. Kota Bambu Utara",
    "tanggal": "",
    "lokasi": "Gg Mawar (Perbatasan kel. kota Bambu Utara dengan kel. Jati pulo)",
    "pelaku": "Warga",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.20422,
    "lng": 106.79468
  },
  {
    "type": "Tawuran",
    "kecamatan": "Palmerah",
    "kelurahan": "Kel.Palmerah",
    "tanggal": "",
    "lokasi": "JI.Raya Palmerah Barat",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.1976,
    "lng": 106.80696
  },
  {
    "type": "Tawuran",
    "kecamatan": "Palmerah",
    "kelurahan": "Kel.Palmerah",
    "tanggal": "",
    "lokasi": "TPU Jl. Kemanggisan Pulo Kel. Palmerah",
    "pelaku": "warga",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.20034,
    "lng": 106.79462
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kembangan",
    "kelurahan": "Kel.Kembangan Selatan",
    "tanggal": "",
    "lokasi": "JI.Kembang Timur dan Barat Rw.02",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.18522,
    "lng": 106.73368
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kembangan",
    "kelurahan": "Kel.Srengseng",
    "tanggal": "",
    "lokasi": "JI.Swadarma Raya Kelurahan Srengseng",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.18698,
    "lng": 106.74062
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel.Kalideres",
    "tanggal": "",
    "lokasi": "JI.Taman Gombol Paya Rt. 010/013",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11956,
    "lng": 106.71326
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel.Pegadungan",
    "tanggal": "",
    "lokasi": "JI.20 Desember RT.0081003",
    "pelaku": "anak/remaja",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.11696,
    "lng": 106.69778
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel.Tegal Alur",
    "tanggal": "",
    "lokasi": "JI.komplek Kebersihan GG. Jangkol RT 08 RW 10 perbatasan Menceng polo (Cengkareng barat) dan Jl. komplek Kebersihan",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.12208,
    "lng": 106.70176
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel.Tegal Alur",
    "tanggal": "",
    "lokasi": "JI. Kamal Benda RT 01 RW 09 perbatasan kelurahan Kamal",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11768,
    "lng": 106.70302
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel.Tegal Alur",
    "tanggal": "",
    "lokasi": "Jl. Kayu Besar Rt03.012 Kel. Tegalalur, Kalideres",
    "pelaku": "kelompok warga",
    "keterangan": "Kelompok Pemuda/Remaja melakukan aksi tawuran pada malam hari Pukul 24.00 s.d 03.00 WIB",
    "lat": -6.11824,
    "lng": 106.70836
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel. Kamal",
    "tanggal": "",
    "lokasi": "JI.Benda Raya Walungan RW.08 Kamal",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11556,
    "lng": 106.70462
  },
  {
    "type": "Tawuran",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel. Kamal",
    "tanggal": "",
    "lokasi": "JI.Kp. Belakang RW.03 Kamal",
    "pelaku": "",
    "keterangan": "",
    "lat": -6.11166,
    "lng": 106.70708
  },
  {
    "type": "Konflik",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. Tanjung Duren Selatan",
    "tanggal": "Rabu/11 Maret 2026",
    "lokasi": "PT. Susu Life Indonesia (Joiway), Ruko Central Park, Jl. Letjen S. Parman Kav. 28, Kel. Tanjung Duren Selatan, Kec. Grogol Petamburan.",
    "pelaku": "Sekelompok warga menyampaikan pendapat terkait permasalahan dugaan pelanggaran perpajakan dan kepabeanan yang dilakukan Garda Muda Indonesia pada pukul 15.30 WIB",
    "keterangan": "Sekelompok warga menyampaikan pendapat terkait permasalahan dugaan pelanggaran perpajakan dan kepabeanan yang dilakukan Garda Muda Indonesia pada pukul 15.30 WIB",
    "lat": -6.17914,
    "lng": 106.78108
  },
  {
    "type": "Konflik",
    "kecamatan": "Grogol Petamburan",
    "kelurahan": "kel. Tanjung Duren Selatan",
    "tanggal": "Rabu/ 11 Maret 2026",
    "lokasi": "APL Tower, Jl. Letjen S. Parman Kav. 28, Kel. Tanjung Duren Selatan, Kec. Grogol Petamburan, Jakarta Barat.",
    "pelaku": "Jaringan Aktivis Peduli Korban Kecelakaan Kerja & Aliansi Vokal Anti Tirani dan Korupsi (Avatar).",
    "keterangan": "Sekelompok warga menyampaikan pendapat terkait permasalahan kecelakaan kerja di PT Borneo Alumindo Prima dan isu korupsi di PT Ciliandra Perkasa yang dilakukan elemen Jaringan Aktivis Peduli Korban Kecelakaan Kerja & Aliansi Avatar pada pukul 15.35",
    "lat": -6.16382,
    "lng": 106.78658
  },
  {
    "type": "Konflik",
    "kecamatan": "Tamansari",
    "kelurahan": "kel. glodok",
    "tanggal": "Rabu/ 11 Maret 2026",
    "lokasi": "PT. Modern Land Realty Tbk, Green Central City, Area Komersil Lt. 5, Jl. Gajah Mada No. 188, Kel. Glodok, Kec. Tamansari, Jakarta Barat.",
    "pelaku": "Serikat Mahasiswa Bergerak",
    "keterangan": "Sekelompok mahasiswa menyampaikan pendapat terkait permasalahan operasional yang dilakukan elemen Serikat Mahasiswa Bergerak pada pukul 13.00 s.d. 15.30 WIB",
    "lat": -6.163,
    "lng": 106.75212
  },
  {
    "type": "Konflik",
    "kecamatan": "Tamansari",
    "kelurahan": "Kel. Tangki",
    "tanggal": "Senin/ 02 Maret 2026",
    "lokasi": "Kantor Lurah Tanki Jl. Mangga Besar 12, RT.6/RW.2, Tangki, Kec. Taman Sari, Kota Jakarta Barat.",
    "pelaku": "WARGA RW 07",
    "keterangan": "sekelompok warga menyampaikan pendapat terkait permasalahan pemukulan yang dilakukan Ketua RW 07 Bpk. Budi Sundono pukul 10.30 sd 11.15 WIB",
    "lat": -6.17226,
    "lng": 106.75594
  },
  {
    "type": "Konflik",
    "kecamatan": "Kalideres",
    "kelurahan": "Kel. Kamal",
    "tanggal": "Kamis/ 05 Maret 2026",
    "lokasi": "Kp. Kebon Dua Ratus, RT. 05/06, Kel. Kamal, Kec. Kalideres.",
    "pelaku": "Dewan Pengurus Pusat Ikatan Mahasiswa Peduli Akan Sosial (DPP-IMPAS)",
    "keterangan": "Sekelompok mahasiswa menyampaikan pendapat terkait permasalahan dugaan pabrik ilegal yang dilakukan Dewan Pengurus Pusat Ikatan Mahasiswa Peduli Akan Sosial (DPP-IMPAS) di wilayah Kec. Kalideres Pukul 12.45 – 13.00 WIB",
    "lat": -6.12754,
    "lng": 106.70544
  }
];
